apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: frontend
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      env: dev
      component: frontend
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        component: frontend
    spec:
      containers:
      - name: frontend
        image: jujjurisowjanya/frontend:1.4.0
        imagePullPolicy: Always
        resources:
          requests:
           memory: "125Mi"
           cpu: "100m"
          limits:
           memory: "256Mi"
           cpu: "200m"
        readinessProbe:
          tcpSocket:
            port: 8080
          periodSeconds: 10
          failureThreshold: 2
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
           path: /health
           port: 8080
          failureThreshold: 2
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
 name: frontend
 namespace: roboshop
 labels:
   project: roboshop
   env: dev
   component: frontend
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    env: dev
    component: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80