apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
  # property-like keys; each key maps to a simple value
    project: roboshop
    env: dev
    component: shipping
data: 
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: shipping
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      env: dev
      component: shipping
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        component: shipping
    spec:
      containers:
      - name: shipping
        image: jujjurisowjanya/shipping:1.5.0
        imagePullPolicy: Always
        resources:
          requests:
           memory: "512Mi"
           cpu: "300m"
          limits:
           memory: "512Mi"
           cpu: "300m"
        readinessProbe:
          tcpSocket:
            port: 8080
          periodSeconds: 10
          failureThreshold: 2
          initialDelaySeconds: 15
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 10
          failureThreshold: 20
        livenessProbe:
          httpGet:
           path: /health
           port: 8080
          failureThreshold: 2
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: shipping
---
apiVersion: v1
kind: Service
metadata:
 name: shipping
 namespace: roboshop
 labels:
   project: roboshop
   env: dev
   component: shipping
spec:
  selector:
    project: roboshop
    env: dev
    component: shipping
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080