apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
data:
  RABBITMQ_DEFAULT_USER: roboshop
  RABBITMQ_DEFAULT_PASS: roboshop123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: rabbitmq
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      env: dev
      component: rabbitmq
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        envFrom:
        - configMapRef:
            name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
 name: rabbitmq
 namespace: roboshop
spec:
  selector:
    project: roboshop
    env: dev
    component: rabbitmq
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672