apiVersion: v1
kind: ConfigMap
metadata:
  name: user-cm
  namespace: roboshop
  labels:
  # property-like keys; each key maps to a simple value
    project: roboshop
    env: dev
    component: user
data: 
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-rs
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: user
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      env: dev
      component: user
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        component: user
    spec:
      containers:
      - name: user
        image: jujjurisowjanya/user:1.4.0
        imagePullPolicy: Always
        resources:
          requests:
           memory: "64Mi"
           cpu: "250m"
          limits:
           memory: "128Mi"
           cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 8080
          periodSeconds: 10
          failureThreshold: 2
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
          path: /health
          port: 8080
        failureThreshold: 2
        periodSeconds: 10
        envFrom:
        - configMapRef:
            name: user-cm
---
apiVersion: v1
kind: Service
metadata:
 name: user-service
 namespace: roboshop
 labels:
   project: roboshop
   env: dev
   component: user
spec:
  selector:
    project: roboshop
    env: dev
    component: user
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080